## Numpy Array

In [ ]:
import numpy as np

In [2]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]

In [4]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [6]:
np_height = np.array(height)

In [7]:
np_height 

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [8]:
np_weight = np.array(weight)

In [22]:
np_weight 

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [24]:
type(np_height)

numpy.ndarray

In [25]:
type(np_weight)

numpy.ndarray

In [10]:
bmi = np_weight / np_height ** 2

In [21]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

## Numpy : remarks

In [12]:
np.array([1.0, "is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

In [13]:
python_list = [1, 2, 3]

In [14]:
numpy_array = np.array([1, 2, 3])

In [15]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [16]:
numpy_array + numpy_array

array([2, 4, 6])

## Numpy Subsetting

In [17]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [18]:
bmi[1]

20.97505668934241

In [19]:
bmi > 23

array([False, False, False,  True, False])

In [20]:
bmi[bmi > 23]

array([24.7473475])

## 2D Numpy Arrays

In [27]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

In [28]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [29]:
np_2d.shape

(2, 5)

In [30]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, "68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

## Subsetting

In [31]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [32]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [33]:
np_2d[0][2]

1.71

In [34]:
np_2d[0,2]

1.71

In [35]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [36]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

# Numpy : Basic Statistics
## City-wide survey

In [37]:
import numpy as np

In [44]:
np_city = np.array([[ 1.64, 71.78 ],
                    [ 1.37, 63.35 ],
                    [ 1.6 , 55.09 ],
                    [ 2.04, 74.85 ],
                    [ 2.04, 68.72 ],
                    [ 2.01, 73.57 ],
                    [ 2.02, 74.5 ]])

In [45]:
np_city

array([[ 1.64, 71.78],
       [ 1.37, 63.35],
       [ 1.6 , 55.09],
       [ 2.04, 74.85],
       [ 2.04, 68.72],
       [ 2.01, 73.57],
       [ 2.02, 74.5 ]])

In [46]:
np.mean(np_city[:,0])

1.817142857142857

In [47]:
np.median(np_city[:,0])

2.01

In [48]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[1.        , 0.68812706],
       [0.68812706, 1.        ]])

In [49]:
np.std(np_city[:,0])

0.25527096447916364

## Generate data

In [50]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)

In [51]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [52]:
np_city = np.column_stack((height, weight))

In [53]:
np_city

array([[ 1.66, 46.66],
       [ 1.99, 75.35],
       [ 1.78, 78.25],
       ...,
       [ 1.72, 70.89],
       [ 1.68, 65.29],
       [ 1.93, 56.58]])